### ISSUE TITLE
Does not handle Vite building

### ISSUE THREAD

**Issue by jarimustonen** [netlify/remix-compute#249]
Remix is in the process of being moving its build process to Vite. At the moment, this adapter does not seem to handle Vite build.

**To Reproduce** Steps to reproduce the behavior:

1. Port the project to use Vite using default instructions here: https://remix.run/docs/en/main/future/vite
2. Update netlify.toml, publish to `build` instead on `public`
3. Deploy site

At this point, Netlify reports that there are no functions deployed.

We, of course, expect the code to deploy normally.

**Comment by serhalp** [comment]
Closed by https://github.com/netlify/remix-compute/pull/251. Please feel free to re-open if this is still not working.
