### ISSUE TITLE
[Vite Plugin] Build produces invalid output on Windows

### ISSUE THREAD

**Issue by wKovacs64** [netlify/remix-compute#263]
**Describe the bug**

After migrating a Remix app to Vite with the Netlify plugin, the built output doesn't seem quite right on Windows (might just be a path resolution issue like always). Dev works fine, but `netlify serve` fails with the following message:

```
Invalid module "....\buildserverserver.js" is not a valid package name imported from C:\dev\test\remix-2.7.2-vite-netlify\.netlify\functions-serve\.unzipped\remix-server\remix-server.mjs
```

And the contents of `.netlify\functions-serve\.unzipped\remix-server\remix-server.mjs` are as follows (which looks very different than on macOS):

```ts
import {createRequire as ___nfyCreateRequire} from "module";
import {fileURLToPath as ___nfyFileURLToPath} from "url";
import {dirname as ___nfyPathDirname} from "path";
let __filename=___nfyFileURLToPath(import.meta.url);
let __dirname=___nfyPathDirname(___nfyFileURLToPath(import.meta.url));
let require=___nfyCreateRequire(import.meta.url);


// .netlify/functions-internal/remix-server.mjs
import { default as default2 } from "....\buildserverserver.js";
var config = {
  name: "Remix server handler",
  generator: "@netlify/remix-adapter@2.3.0",
  path: "/*",
  preferStatic: true
};
export {
  config,
  default2 as default
};
```

**To Reproduce** Steps to reproduce the behavior:

On Windows...

1. `npx create-remix@latest --template netlify/remix-template`
2. `npm run start`

**Expected behavior**

I expect it to work (like it does on macOS).

**Screenshots**

![image](https://github.com/netlify/remix-compute/assets/1288694/671ff0ce-f6a1-4fdd-b0ec-fc5c7aa022c9)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: N/A
- Version: `@netlify/remix-adapter@2.3.0`

**Comment by mrstork** [comment]
This looks to be the same issue as https://github.com/netlify/remix-compute/issues/275 which has been resolved in https://github.com/netlify/remix-compute/pull/281.

Please ensure you are using `@netlify/remix-adapter@2.3.1` which includes the fix. Running `npm install` in the project directory should automatically install the latest version for you, or you could remake the project with the same `netlify/remix-template` as you did before.
