### ISSUE TITLE
Update Remix and re-export it's additional functions and types from the "@netlify/remix-runtime" package

### ISSUE THREAD

**Issue by petervmeijgaard** [netlify/remix-compute#338]
**Is your feature request related to a problem? Please describe.**

I saw that the Netlify Remix runtime was out-of-date with the `@remix-run/server-runtime` package. A few types and functions are currently missing from the `@netlify/remix-runtime` that are included in the `@remix-run/server-runtime` package.

**Describe the solution you'd like**

By bumping the `@remix-run/*`packages and re-exporting all the added functions and types from the `@netlify/remix-runtime` package, the package will be up-to-date again.

**Describe alternatives you've considered**

None. I don't see any alternatives regarding this problem. Or forcing the users to also include `@remix-run/server-runtime` in their project and using exports from that package instead.

**Additional context**

--

**Comment by serhalp** [comment]
Closed by #339.
