### ISSUE TITLE
Named export 'unstable_defineAction' not found

### ISSUE THREAD

**Issue by ashea29** [netlify/remix-compute#458]
### **Describe the bug**:
When following the guide on [deploying Shopify Hydrogen to Netlify](https://developers.netlify.com/guides/how-to-deploy-a-shopify-hydrogen-storefront-to-netlify/), running the command `netlify dev` produces the following error in the browser:

```
Named export 'unstable_defineAction' not found. The requested module '@remix-run/server-runtime' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@remix-run/server-runtime';
```

In addition, the CLI shows:

```
 »   Error: There was a problem setting up the Edge Functions environment. To try a manual installation, visit https://ntl.fyi/install-deno.
11:02:46 AM [vite] Error when evaluating SSR module /app/root.tsx: failed to import "@netlify/remix-runtime"
|- file:///C:/Users/[path-to-my-codebase]/node_modules/@netlify/remix-runtime/dist/index.mjs:68
  unstable_defineAction,
  ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'unstable_defineAction' not found. The requested module '@remix-run/server-runtime' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@remix-run/server-runtime';
```

### **To Reproduce**:
Following the steps from the [guide](https://developers.netlify.com/guides/how-to-deploy-a-shopify-hydrogen-storefront-to-netlify/) referenced above, the error can be reproduced by running `netlify dev`.

### **What I tried**:
First, though I was pretty sure it wouldn't help, I tried installing Deno as the CLI error seemed to suggest... which didn't resolve the issue. Then, after doing a Google search I ran across a reference to some [troubleshooting steps](https://remix.run/docs/en/main/guides/vite#troubleshooting) in the Remix docs regarding Vite, which also didn't resolve the issue.

To investigate further, I went into my `node_modules` to look at the '@netlify/remix-runtime' and '@remix-run/server-runtime' packages. '@netlify/remix-runtime' does indeed try to import then export a couple things which aren't actually exported from '@remix-run/server-runtime':
- unstable_defineAction
- unstable_defineLoader

### **Expected behavior**:
To be able to run the development server using `netlify dev` without errors.

### **Environment:**
- **OS**: Windows
- **Browser**: Chrome
- **Node.js Version**: 20.10.0

**Comment by serhalp** [comment]
Hey @ashea29, thanks for reading my guide and for this great bug report!

Great catch! It looks like Remix removed these unstable exports last week in 2.12.0. I've just removed them from our packages, so this should be fixed as of a couple minutes ago. I just ran the steps in the guide again to verify and it's working.

Sorry for the trouble. :)

**Comment by ashea29** [comment]
No worries :) Thank you!
