### ISSUE TITLE
Cypress always fails on main waiting on deploy preview

### ISSUE THREAD

**Issue by nickytonline** [netlify/remix-compute#52]
When there are pull requests (PR), the deploy preview for a pull request deploys in a timely manner and the Cypress E2E tests pass in our GitHub action. For some reason, once a PR is merged, the deploy preview takes longer than expected and the Cypress tests fail because the deploy preview is not ready in a timely manner.

I haven't had time to look into this yet, but it'd be good to get this sorted. Here is an example of a failure:

This PR's deploy preview and Cypress tests pass fine https://github.com/netlify/remix-compute/pull/49

However, when merged, here is the result https://github.com/netlify/remix-compute/actions/runs/4228571747/jobs/7344140750#step:22:133

```bash
Prepare all required actions
Getting action download info
Download action repository 'tj-actions/branch-names@v6' (SHA:eee8675bd61ec38bcfbfedd504d8473[2](https://github.com/netlify/remix-compute/actions/runs/4228571747/jobs/7344140750#step:6:2)92ba649e)
Download action repository 'actions/github-script@v6' (SHA:98814c5[3](https://github.com/netlify/remix-compute/actions/runs/4228571747/jobs/7344140750#step:6:3)be79b1d30f795b907e553d86793[4](https://github.com/netlify/remix-compute/actions/runs/4228571747/jobs/7344140750#step:6:4)[5](https://github.com/netlify/remix-compute/actions/runs/4228571747/jobs/7344140750#step:6:5)975)
Run ./.github/actions/wait-for-netlify-deploy
Run tj-actions/branch-names@v6
Run # "Set branch names..."
Run # "Set the current branch name..."
Run # "Set the default branch name..."
Run # "Set the tag name..."
Run actions/github-script@v6
Waiting for Netlify deploy.
  Check the queue: https://app.netlify.com/sites/remix-edge/deploys
Error: Timeout exceeded
```

**Comment by serhalp** [comment]
Superseded/fixed by https://github.com/netlify/remix-compute/pull/316
